"""Initial schema

Revision ID: 82107e6cecba
Revises: 
Create Date: 2026-05-20 06:39:19.905335
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82107e6cecba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('raw_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False, comment="'scraper' or 'manual_upload'"),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment="'pending', 'processed', or 'failed'"),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('username_enc', sa.String(length=500), nullable=False),
    sa.Column('password_enc', sa.String(length=500), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scrape_status', sa.String(length=20), nullable=False, comment="'pending', 'success', 'failed', or 'disabled'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_player_id'), 'credentials', ['player_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('tee_box', sa.String(length=50), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('total_putts', sa.Integer(), nullable=True),
    sa.Column('date_played', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_date_played'), 'rounds', ['date_played'], unique=False)
    op.create_index(op.f('ix_rounds_player_id'), 'rounds', ['player_id'], unique=False)
    op.create_table('hole_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('putts', sa.Integer(), nullable=True),
    sa.Column('fairway_hit', sa.Boolean(), nullable=True),
    sa.Column('gir', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'hole_number', name='uq_round_hole')
    )
    op.create_index(op.f('ix_hole_scores_round_id'), 'hole_scores', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hole_scores_round_id'), table_name='hole_scores')
    op.drop_table('hole_scores')
    op.drop_index(op.f('ix_rounds_player_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_date_played'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_credentials_player_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_table('raw_imports')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
